# Generated by Django 5.2.7 on 2025-10-13 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đối tác')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('type', models.CharField(choices=[('clothing', 'Clothing'), ('printing', 'Printing'), ('flower', 'Flower'), ('venue', 'Venue'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=50, verbose_name='Loại đối tác')),
                ('cost', models.CharField(help_text="Có thể là số hoặc 'Theo bill'", max_length=100, verbose_name='Chi phí')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Format: {phone, email, address, website, contact_person}', verbose_name='Thông tin liên hệ')),
                ('bank_account', models.JSONField(blank=True, default=dict, help_text='Format: {bank_name, account_number, account_holder}', verbose_name='Thông tin ngân hàng')),
                ('business_info', models.JSONField(blank=True, default=dict, help_text='Format: {tax_code, business_license, established_date}', verbose_name='Thông tin doanh nghiệp')),
                ('rating', models.FloatField(default=0, help_text='Từ 0 đến 5', verbose_name='Đánh giá')),
                ('projects_count', models.IntegerField(default=0, verbose_name='Số dự án')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng doanh thu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('agreements', models.JSONField(blank=True, default=list, help_text='Format: [{title, file_url, start_date, end_date, terms}]', verbose_name='Hợp đồng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'db_table': 'partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
