# Generated by Django 5.2.7 on 2025-10-13 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã dự án')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('package_name', models.CharField(max_length=200, verbose_name='Tên gói')),
                ('package_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gói')),
                ('package_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('package_final_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá cuối cùng')),
                ('additional_packages', models.JSONField(blank=True, default=list, help_text='Format: [{package_type, package_name, package_price, package_discount, package_final_price, team, notes}]', verbose_name='Gói bổ sung')),
                ('payment', models.JSONField(blank=True, default=dict, help_text='Format: {status, deposit, final, paid, payment_history[{amount, date, method, notes, received_by}]}', verbose_name='Thanh toán')),
                ('shoot_date', models.DateField(verbose_name='Ngày chụp')),
                ('shoot_time', models.CharField(blank=True, max_length=50, verbose_name='Giờ chụp')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Địa điểm')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Format: {shooting_done, retouch_done, delivered}', verbose_name='Tiến độ')),
                ('milestones', models.JSONField(blank=True, default=list, help_text='Format: [{name, description, stage, status, team, start_date, due_date, completed_date, completed_by, notes}]', verbose_name='Cột mốc')),
                ('team', models.JSONField(blank=True, default=dict, help_text='Format: {main_photographer:{employee, salary, bonus, notes}, assist_photographers[], makeup_artists[], retouch_artists[]}', verbose_name='Đội ngũ')),
                ('partners', models.JSONField(blank=True, default=dict, help_text='Format: {clothing[{partner, actual_cost}], printing:{included, actual_cost}, flower:{included, actual_cost}, total_cost, notes[]}', verbose_name='Đối tác')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('files', models.JSONField(blank=True, default=list, help_text='Format: [{type, url, uploaded_at}]', verbose_name='Files')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('update_history', models.JSONField(blank=True, default=list, help_text='Format: [{date, user, action, notes, changes}]', verbose_name='Lịch sử cập nhật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
