# Generated by Django 5.2.7 on 2025-10-13 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa cuối'),
        ),
        migrations.AddField(
            model_name='project',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='packages.package', verbose_name='Loại gói'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-shoot_date'], name='projects_status_f0664e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['customer_name', 'customer_phone'], name='projects_custome_4348d3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', '-created_at'], name='projects_created_fc9bc6_idx'),
        ),
    ]
