# Generated by Django 5.0.1 on 2025-11-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
