# Generated by Django 5.0.1 on 2025-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shoot_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Giờ chụp'),
        ),
    ]
