# Generated by Django 5.2.7 on 2025-10-13 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã gói')),
                ('name', models.CharField(max_length=200, verbose_name='Tên gói')),
                ('category', models.CharField(choices=[('portrait', 'Portrait'), ('family', 'Family'), ('couple', 'Couple'), ('wedding', 'Wedding'), ('event', 'Event'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=50, verbose_name='Danh mục')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Format: {photo, makeup, assistant, retouch, time, location, retouch_photos, extra_services[]}', verbose_name='Chi tiết gói')),
                ('includes', models.JSONField(blank=True, default=list, help_text='Danh sách dịch vụ bao gồm', verbose_name='Bao gồm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='Điểm phổ biến')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Gói chụp',
                'verbose_name_plural': 'Gói chụp',
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
