# Generated by Django 5.2.7 on 2025-10-13 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'category'], name='packages_is_acti_a93116_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['name'], name='packages_name_2c850c_idx'),
        ),
    ]
