# Generated by Django 5.2.7 on 2025-10-13 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7, verbose_name='Tháng')),
                ('total_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng lương')),
                ('breakdown', models.JSONField(default=dict, help_text='Format: {base_salary, project_salaries[], total_bonus, deductions, net_salary}', verbose_name='Chi tiết')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Phương thức thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Lương tháng',
                'verbose_name_plural': 'Lương tháng',
                'db_table': 'monthly_salaries',
                'ordering': ['-month', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7, verbose_name='Tháng')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thưởng')),
                ('work_type', models.CharField(choices=[('mainPhotographer', 'Main Photographer'), ('assistPhotographer', 'Assist Photographer'), ('makeupArtist', 'Makeup Artist'), ('retouchArtist', 'Retouch Artist'), ('other', 'Other')], max_length=50, verbose_name='Loại công việc')),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng (ảnh retouch, ngày làm việc, etc.)', verbose_name='Số lượng')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Lương',
                'verbose_name_plural': 'Lương',
                'db_table': 'salaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
