# Generated by Django 5.2.7 on 2025-10-13 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('projects', '0002_initial'),
        ('salaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salaries', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AddField(
            model_name='salary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='projects.project', verbose_name='Dự án'),
        ),
        migrations.AddIndex(
            model_name='monthlysalary',
            index=models.Index(fields=['month'], name='monthly_sal_month_a2122c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysalary',
            index=models.Index(fields=['employee', 'month'], name='monthly_sal_employe_b0dc65_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysalary',
            index=models.Index(fields=['is_paid'], name='monthly_sal_is_paid_f2d5c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalary',
            unique_together={('employee', 'month')},
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'month'], name='salaries_employe_8d57b1_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['project'], name='salaries_project_b56fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['month'], name='salaries_month_0854d7_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['is_paid'], name='salaries_is_paid_622902_idx'),
        ),
    ]
