# Generated by Django 5.0.1 on 2025-11-10 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('salaries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlysalary',
            name='monthly_sal_is_paid_f2d5c4_idx',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='breakdown',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thưởng'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Khấu trừ'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='projects_detail',
            field=models.JSONField(default=list, help_text='Format: [{project_id, project_name, salary}]', verbose_name='Chi tiết dự án'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng lương'),
        ),
        migrations.AddIndex(
            model_name='monthlysalary',
            index=models.Index(fields=['status'], name='monthly_sal_status_c2548e_idx'),
        ),
    ]
