# Generated by Django 5.0.1 on 2025-11-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_remove_monthlysalary_monthly_sal_is_paid_f2d5c4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phương thức thanh toán'),
        ),
    ]
