# Generated by Django 5.2.7 on 2025-10-13 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhân viên')),
                ('role', models.CharField(choices=[('Photo/Retouch', 'Photo/Retouch'), ('Makeup Artist', 'Makeup Artist'), ('Sales', 'Sales'), ('Manager', 'Manager'), ('Content', 'Content'), ('Designer', 'Designer')], max_length=50, verbose_name='Vai trò')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Kỹ năng')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('bank_account', models.JSONField(blank=True, default=dict, help_text='Format: {bank_name, account_number, account_holder}', verbose_name='Thông tin ngân hàng')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='Format: {name, phone, relationship}', verbose_name='Liên hệ khẩn cấp')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('default_rates', models.JSONField(blank=True, default=dict, help_text='Format: {main_photo, assist_photo, retouch, makeup}', verbose_name='Đơn giá mặc định')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
